"use client";

import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { DocumentPreview } from "@/components/documents/DocumentPreview";
import { DownloadButton } from "@/components/documents/DownloadButton";
import { getFunction } from "@/services/api";

const REPO = "D:\\vortex\\project\\backend";

export default function DocumentsPage() {
  const params       = useSearchParams();
  const functionName = params.get("fn") ?? "";
  const filepath     = params.get("filepath") ?? "";

  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState<string | null>(null);
  const [docData,  setDocData] = useState<{
    markdown: string;
    json: object;
    primaryOwner: string;
    generatedAt: string;
  } | null>(null);

  useEffect(() => {
    if (!functionName || !filepath) {
      setLoading(false);
      return;
    }

    getFunction(REPO, filepath, functionName)
      .then(data => {
        const log = data.decision_log;

        if (!log) {
          setError("No decision log found. Run explain-function first.");
          return;
        }

        // Build markdown string from the decision log
        const keyDecisionsMarkdown = log.key_decisions
          .map((d: string, i: number) => `- **Decision ${i + 1}** — ${d}`)
          .join("\n");

        const linkedIssuesMarkdown = log.linked_issues.length
          ? log.linked_issues.map((i: string) => `\`${i}\``).join(", ")
          : "None";

        const markdown = `# ${functionName}

## Why It Exists

${log.why_it_exists}

## Key Decisions

${keyDecisionsMarkdown}

## Linked Issues

${linkedIssuesMarkdown}

## Blast Radius

${(data.analysis?.blast_radius ?? []).map((fn: string) => `\`${fn}\``).join(", ") || "None identified."}

---

*Generated by Vortex · ${new Date(log.generated_at).toLocaleDateString()}*
`;

        setDocData({
          markdown,
          json: {
            function_name:  functionName,
            why_it_exists:  log.why_it_exists,
            key_decisions:  log.key_decisions,
            linked_issues:  log.linked_issues,
            generated_at:   log.generated_at,
            blast_radius:   data.analysis?.blast_radius ?? [],
            primary_owner:  data.ownership?.primary_owner ?? "unknown",
            confidence:     data.ownership?.confidence ?? 0,
          },
          primaryOwner: data.ownership?.primary_owner ?? "unknown",
          generatedAt:  log.generated_at,
        });
      })
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, [functionName, filepath]);

  // ── No function selected ──────────────────────────────────────────────────

  if (!functionName || !filepath) {
    return (
      <div className="p-8 flex flex-col items-center justify-center h-full gap-3">
        <p className="font-mono text-xs text-[#6b6b6b]">
          No function selected.
        </p>
        <p className="font-mono text-[10px] text-[#3e3e42]">
          Navigate here from the inspector or dashboard.
        </p>
      </div>
    );
  }

  // ── Loading ───────────────────────────────────────────────────────────────

  if (loading) {
    return (
      <div className="p-6 h-screen flex flex-col gap-4">
        <div className="h-10 w-48 bg-[#252526] border border-[#3e3e42] rounded-sm animate-pulse" />
        <div className="flex-1 bg-[#252526] border border-[#3e3e42] rounded-sm animate-pulse" />
      </div>
    );
  }

  // ── Error ─────────────────────────────────────────────────────────────────

  if (error || !docData) {
    return (
      <div className="p-8">
        <p className="font-mono text-xs text-[#f48771]">
          {error ?? "Could not load document."}
        </p>
      </div>
    );
  }

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="p-6 h-screen flex flex-col gap-4">

      {/* Download button row */}
      <div className="flex items-center gap-3 shrink-0">
        <span className="font-mono text-[10px] uppercase tracking-widest text-[#6b6b6b]">
          export
        </span>
        <DownloadButton
          filename={`${functionName}-decision-log`}
          markdownContent={docData.markdown}
          jsonContent={docData.json}
          onDownload={(fmt) => console.log("pdf download requested", fmt)}
        />
      </div>

      {/* Document preview */}
      <div className="flex-1 min-h-0">
        <DocumentPreview
          title={`${functionName} — Decision Log`}
          functionName={functionName}
          filepath={filepath}
          primaryOwner={docData.primaryOwner}
          generatedAt={docData.generatedAt}
          markdownContent={docData.markdown}
          onDownload={() => console.log("download clicked")}
        />
      </div>

    </div>
  );
}